#!/bin/bash

set -e

while read -r line; do
	case "$line" in
	*.zip) : flashablezip ;;
	*gxp) : gearlockgxp ;;
	esac
	/usr/lib/gearlock/compat/"$_"/install "$line"
done

printf "\nimport /data/adb/gearlock%s\n" /etc/init/gearlock/*.rc >/etc/init/sources.rc
