#!/bin/bash

set -e

install_kernel() { mkinitfs -k "$(basename "$1")";}

remove_kernel() {
	filelist=("/boot/vmlinuz-${1}"
		"/boot/initrd-${1}.img"
		"/efi/EFI/Android/vmlinuz-${1}.efi")

	# access all the files to trigger any potential automounts
	stat -- /boot/ /efi/ "${filelist[@]}" &>/dev/null

	# remove the actual kernel and images for the package being removed
	rm -f -- "${filelist[@]}"
}

while read -r line; do
	[[ "$line" = */vmlinuz ]] || continue

	case "$1" in
	install) install_kernel "$(dirname "$line")" ;;
	remove) remove_kernel "$(dirname "$line")" ;;
	esac
done

[ "$1" = regen ] && mkinitfs -a
