#!/bin/bash

usage() {
	echo
}

while getopts "A:adpvh" opt; do
	case "$opt" in
	A) ARCH="$OPTARG" ;;
	a) : "APKBUILD" ;;
	d) : "DEBIAN" ;;
	p) : "PKGBUILD" ;;
	v) : "XBPS" ;;
	h) usage && exit ;;
	*) usage && exit 1 ;;
	esac
	TYPE=$_
done
shift $((OPTIND - 1))

FILE=$1

if [ ! "$TYPE" ]; then
	for cmd in pacman xbps-src dpkg apk; do
		command -v $cmd || continue
		case "$cmd" in
		pacman) : "PKGBUILD" ;;
		xbps) : "XBPS" ;;
		dpkg) : "DEBIAN" ;;
		apk) : "APKBUILD" ;;
		esac
		TYPE=$_
		break
	done
fi

: "${ARCH:="$(busybox arch)"}"

if grep -q " ROOT=" /proc/cmdline 2>/dev/null; then
	TMPDIR=$SRCDIR/tmp
	[ -d "$TMPDIR" ] || mkdir -p "$TMPDIR"
else
	TMPDIR=/data/local/tmp
fi

# FREESPACES and FREESPACE are different
FREESPACES=($("$GEARLIB"/checkfree))

NEEDED_SPACE=$("$GEARLIB"/decompsize "$FILE")

if [ "$COPYTORAM" = true ]; then
	TMPSPACE=${FREESPACES[1]}
	((NEEDED_SPACE > TMPSPACE)) &&
		echo "COPYTORAM is enabled, but there's not enough RAM to perform this action, falling back..." &&
		TMPSPACE=${FREESPACES[0]} ||
		mount -t tmpfs -o rw,nodev,nosuid,size=$((TMPSPACE + 4096))K,mode=1770 tmpfs "$TMPDIR"
	FREESPACE=$TMPSPACE
else
	FREESPACE=${FREESPACES[0]}
fi

((NEEDED_SPACE > FREESPACE)) &&
	exit 3

# TODO: extract in RAM

"$GEARLIB"/extract "$FILE" "$TMPDIR"

if [ -e "$TMPDIR/module.prop" ]; then
	eval "$(sed -r "s/^([a-zA-Z0-9_]+[a-zA-Z0-9_-]*=)(.*)$/\1\"\2\"/g" "$TMPDIR/module.prop" | tr '\n' ' ')"
else
	echo
fi

# TODO: simulate a magisk/ksu environment to install flashable zips

mkdir -p "$TMPDIR/$GEARDATA/extension/"

# first extract zip/brotli, then create binded package, then install it
