#!/bin/sh

case "$1" in
post-commit)
  printf "# Must include prefix /data/adb/gearlock\n\n"
	for src in /etc/init/gearlock/*.rc; do
    printf "\nimport /data/adb/gearlock%s\n" "$src"
  done
	;;
esac
