#!/usr/bin/busybox sh

export PATH=/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin

case "$1" in
post-commit) busybox find /etc/init/gearlock -type f -exec printf "\nimport /data/adb/gearlock%s\n" {} + >/etc/init/sources.rc || : ;;
esac

exit 0
