#!/bin/sh

auto_detect() {
  tmp=/tmp/dev2mod
  echo 'dev2mod() { while read dev; do case $dev in' >$tmp
  sort -r /lib/modules/$(uname -r)/modules.alias |
    sed -n 's/^alias  *\([^ ]*\)  *\(.*\)/\1)busybox modprobe \2;;/p' >>$tmp
  echo 'esac; done; }' >>$tmp
  for f in $(grep -Eh "drm_kms|sound.core|hyperv" /lib/modules/$(uname -r)/modules.dep | cut -d. -f1); do
    sed -i "/$(basename $f | sed 's/-/_/g')/d" $tmp
  done
  . $tmp
  cat /sys/bus/*/devices/*/uevent | grep MODALIAS | sed 's/^MODALIAS=//' | awk '!seen[$0]++' | dev2mod
  cat /sys/devices/virtual/wmi/*/modalias | dev2mod
}

mount_sdcard() {
  mountpoint -q sdcard && return
  if [ "$SDCARD" ] && [ -e "/mnt/$SRC$SDCARD" ]; then
    [ -e "/android$SDCARD" ] && return
    remount_rw
    sddir=$(dirname $SDCARD)
    mkdir /android$sddir
    mount --bind /mnt/$SRC$sddir /android$sddir
  elif [ "$SDCARD" = "premount" ]; then
    # WARNING: premount the sdcard is deprecated since froyo-x86.
    # It is left only for backward compatibility and may be removed
    # in the future.
    if [ -d "/mnt/$SRC/sdcard" ]; then
      # remount_rw
      mount --bind "/mnt/$SRC/sdcard" mnt/sdcard
    elif [ -d data/sdcard ]; then
      mount --bind data/sdcard mnt/sdcard
    else
      mount -o mode=2777,uid=1000,gid=1015 -t tmpfs tmpfs mnt/sdcard
    fi
  fi
}

setup_tslib() {
  # setup for pointercal
  [ "$BOARD_USES_TSLIB" ] || return
  TSLIBPATH=data/system/tslib

  [ -e $TSLIBPATH/pointercal ] && return
  mkdir -p $TSLIBPATH
  if [ -z "$CALIBRATE" ] && ls system/etc/pointercal*; then
    board=$(cat /sys/class/dmi/id/product_name)
    [ -e system/etc/pointercal.$board ] && pointercal=system/etc/pointercal.$board
    [ -e system/etc/pointercal ] && pointercal=system/etc/pointercal
  fi
  if [ "$pointercal" ]; then
    cp "$pointercal" $TSLIBPATH/pointercal
  elif [ -e system/etc/ts.env ]; then
    ln -s android/data /
    mkdir /dev/graphics /dev/input
    ln -s /dev/fb* /dev/graphics
    ln -s /dev/event* /dev/input
    ts_calibrate >/tmp/cal.log
  fi
  chmod 664 $TSLIBPATH/pointercal
  chown 1000.1000 data data/system $TSLIBPATH
}

run_latehook() {
  if [ "$AUTO_LOAD" = "old" ]; then
    auto_detect
  fi

  # 3G modules
  for m in $EXTMOD; do
    busybox modprobe $m
  done

  mount_sdcard
  setup_tslib
}
