#!/bin/bash

NEWIMG=$1

loop_mount() {
	local disktmp
	disktmp="$(mktemp)"
	rm -f "$disktmp"
	mkdir -p "$disktmp" || true
	mount -o ro${2:+,$2} -t "${3:-auto}" "$1" "$disktmp" 2>/dev/null
	UNMOUNT_LIST="$disktmp $UNMOUNT_LIST"
	echo "$disktmp"
}

patch_img() {

	# APK package patching
	# basically, no package needs to have file path in /system,
	"$GEARDATA"/extensions/execute "$NEWIMG/"

	# addon.d included
}

fsize() { du -sk "$1" | cut -f 1; }

# TODO: rewrite this func to raise NEWIMG by the size of its module
# checkimg() {
# 	newsize=$(($(fsize "$NEWIMG") + total_psize))
# 	"$GEARLIB"/checkfree "$newsize" || exit 1
# 	resize2fs "$NEWIMG" ${newsize}K
# 	NEWIMG=$(loop_mount "$NEWIMG")
# }

# total_psize=$(du -sck $(sed -n 's|^system|/system/p' "$GXP_DB"/*/files) | tail -1 | cut -f 1)

case "$(blkol TYPE "$NEWIMG")" in
ext*) checkimg && is_img=true ;;
esac

patch_img

[ "$is_img" ] && umount -l "$NEWIMG"
