#!/bin/bash

die() { echo "$*" >&2 && exit "${2:-1}"; }

# TODO: signature verification
"$GEARLIB"/checksum "$1" "$2" ||
	die "Signature verification failed" 2

NEWIMG=$1
shift

"$GEARLIB"/checkfree "$(du -sk "$NEWIMG" | awk '{print $1}')" ||
	die "Not enough space to update system image" 1

[ "$SYSTEM_TYPE" = dir ] || COMP=.$SYSTEM_TYPE

# Moves a to b then moves new img to a
rm -f "$SRCDIR/system_b$COMP" 2>/dev/null
mv "$SYSTEM" "$SRCDIR/system_b$COMP"
mv "$NEWIMG" "$SYSTEM"

printf 'processed'
