#!/bin/bash

die() { echo "$*" >&2 && exit 1; }

NEWIMG=$1
NEWIMGSIZE=$(du -sk "$NEWIMG" | awk '{print $1}')
shift

[ "$SYSTEM_TYPE" != dir ] && COMP=.$SYSTEM_TYPE

other() { THE_OTHER=$SRCDIR/system_$1$COMP; }

echo "$SYSTEM" | grep -qE '_a(\.(img|[se]fs))?$' && other b || other a

[ -e "$THE_OTHER" ] && rm -rf "$THE_OTHER"

FREESPACE=$("$GEARLIB"/checkfree)

((NEWIMGSIZE > FREESPACE)) &&
  die "Not enough space to update system image"

mv "$NEWIMG" "$THE_OTHER"
