#!/bin/bash

die() { echo "$*" >&2 && exit "${2:-1}"; }

"$GEARLIB"/checksum "$1" "$2" ||
	die "Signature verification failed" 2

NEWIMG=$1
shift

"$GEARLIB"/checkfree "$(du -sk "$NEWIMG" | awk '{print $1}')" "$SRCDIR" >/dev/null ||
	die "Not enough space to update system image" 1

[ "$SYSTEM_TYPE" = dir ] || COMP=.$SYSTEM_TYPE

# Moves a to b then moves new img to a
# rm -f "$SRCDIR/system_b$COMP" 2>/dev/null
# mv "$SYSTEM" "$SRCDIR/system_b$COMP"
# mv "$NEWIMG" "$SYSTEM"
#
#
MODEFILE=/var/gearlock/active
[ -e $MODEFILE ] &&
	. $MODEFILE ||
	ACTIVE=a

case "$ACTIVE" in a) : b ;; b) : a ;; esac
ACTIVE=$_

mv -f "$NEWIMG" "$SRCDIR/system_$ACTIVE$COMP" &&
	echo "ACTIVE=$ACTIVE" >$MODEFILE &&
	set-active-grub "$ACTIVE"

printf 'processed'
