#!/bin/bash

die() { echo "$*" >&2 && exit 1; }

NEWIMG=$1
NEWIMGSIZE=$(du -sk "$NEWIMG" | awk '{print $1}')
shift

checkspace() {
	"$GEARLIB"/checkfree "$NEWIMGSIZE" ${1} ||
		die "Not enough space to update system image"
}

case "$SYSTEM" in
/dev/*)
	SYSTEM=$(resolve_device "$SYSTEM")
	checkspace "$SYSTEM"

	if mountpoint -q /android; then
		echo "WARNING: Cannot live replace mounted system partition. Scheduled to process next boot..."
		checkspace /var/gearlock
		mv "$NEWIMG" /var/gearlock/system.img
		add_gqueue sysup /var/gearlock/system.img
	else
		dd if="$NEWIMG" of="$SYSTEM" bs=1M status=progress
		yes | fsck -fvy "$SYSTEM"
	fi
	;;
*)
	[ "$SYSTEM_TYPE" != dir ] && COMP=.$SYSTEM_TYPE

	SYSTEM=$SRCDIR/system$COMP
	checkspace

	if mountpoint -q /android; then
		mv -f "$SYSTEM" "$SYSTEM-pending_remove"
		add_gqueue clean
	else
		rm -rf "$SYSTEM"
	fi
	mv "$NEWIMG" "$SYSTEM"
	;;
esac
