#!/bin/bash

die() {
	echo "$*" >&2 &
	exit 1
}

NEWIMG=$1
NEWIMGSIZE=$(du -sk "$NEWIMG" | awk '{print $1}')
shift

checkspace() {
	"$GEARLIB"/checkfree "$NEWIMGSIZE" ${1} ||
		die "Not enough space to update system image"
}

case "$SYSTEM" in
/dev/*)
	SYSTEM=$(resolve_device "$SYSTEM")
	checkspace "$SYSTEM"

	if [ "$BOOTED" ]; then
		# TODO: add system update to queue
		die "Cannot live replace system partition"
	else
		dd if="$NEWIMG" of="$SYSTEM" bs=1M status=progress
		yes | fsck -fvy "$SYSTEM"
	fi
	;;
*)
	[ "$SYSTEM_TYPE" != dir ] && COMP=.$SYSTEM_TYPE

	SYSTEM=$SRCDIR/system$COMP
	checkspace

	if [ "$BOOTED" ]; then
		mv -f "$SYSTEM" "$SYSTEM-pending_remove"
	else
		rm -rf "$SYSTEM"
	fi
	mv "$NEWIMG" "$SYSTEM"
	;;
esac
