#!/bin/bash

die() { echo "$*" >&2 && exit "${2:-1}"; }

# TODO :signature verification
"$GEARLIB"/checksum "$1" "$2" ||
	die "Signature verification failed" 2

NEWIMG=$1
NEWIMGSIZE=$(du -sk "$NEWIMG" | awk '{print $1}')
SIG=$2
shift 2

checkspace() {
	"$GEARLIB"/checkfree "$NEWIMGSIZE" "$1" >/dev/null ||
		die "Not enough space to update system image"1
}

case "$SYSTEM" in
/dev/*)
	SYSTEM=$(resolve_device "$SYSTEM")
	checkspace "$SYSTEM"

	if mountpoint -q /android; then
		echo "WARNING: Cannot live replace mounted system partition. Scheduled to process next boot..." >&2
		checkspace /var/gearlock
		queued_img=/var/gearlock/system.img
		mv "$NEWIMG" "$queued_img"
		mv "$SIG" "$queued_img".sig
		add_gqueue sysup "$queued_img"
		printf 'Scheduled'
	else
		dd if="$NEWIMG" of="$SYSTEM" bs=1M status=progress &&
			yes | fsck -fvy "$SYSTEM" &&
			printf 'processed'
	fi
	;;
*)
	[ "$SYSTEM_TYPE" = dir ] || COMP=.$SYSTEM_TYPE

	SYSTEM=$SRCDIR/system$COMP
	checkspace "$SRCDIR"

	if mountpoint -q /android; then
		mv -f "$SYSTEM" "$SYSTEM-pending_remove"
		add_gqueue clean
	else
		rm -rf "$SYSTEM"
	fi
	mv "$NEWIMG" "$SYSTEM" &&
		printf 'processed'
	;;
esac
