#!/bin/bash

storage_free() {
	if [ ! "$1" ] || [ -d "$1" ]; then
		df -k "${1:-"$(dirname "$TMPDIR")"}" | awk '{print $4}' | tail -1
	elif [ -b "$1" ]; then
		echo "$(($(blockdev --getsz "$1") / 2))"
	else
		du -k "$1" | awk '{print $1}'
	fi
}

ram_free() {
	# temporarily free up ram
	sync
	echo 1 >/proc/sys/vm/drop_caches
	free -k | grep Mem | awk '{print $3}'
}

NEEDED_SPACE=$1 # in Kilobytes
TMPDIR=${2:-$(tmpdir)}

if [ -z "$2" ] && [ "$COPYTORAM" = true ]; then
	((NEEDED_SPACE < $(ram_free))) &&
		mount -t tmpfs -o rw,nodev,nosuid,size=$((NEEDED_SPACE + 4096))K,mode=1770 tmpfs "$TMPDIR" &&
		echo "$TMPDIR" &&
		exit 0

	echo "COPYTORAM is enabled, but there's not enough RAM to perform this action, falling back..." >&2
fi

FREESPACE=$(storage_free "$2")
((NEEDED_SPACE > FREESPACE)) && exit 1

echo "$TMPDIR"
