#!/bin/sh
# busybox-compatible file extract tool for different file types

quit() {
	echo "ERROR: unsupported format '$IN'"
	exit 127
}

while [ "$1" ]; do
	case "$1" in
	-f) FILES=${2//,/ } && shift ;;
	*) [ "$IN" ] && OUT=$1 || IN=$1 ;;
	esac
	shift
done

[ "$OUT" ] && mdkir -p "$OUT"

case "$IN" in
*.t[gx]z | *.tar | *.tar.[gx]z | *.tar.lzma | *.tar.bz2)
	tar ${OUT:+-C "$OUT"} -xaf "$IN" $FILES
	;;
*.t7z | *.tar.7z)
	7z x -so "$IN" | tar ${OUT:+-C "$OUT"} -xf - $FILES
	;;
*.tar.*)
	case "$IN" in
	*.br) COMD=brotli ;;
	*.lz) COMD=lzip ;;
	*.lzo) COMD=lzop ;;
	*.lz4) COMD=lz4 ;;
	*.zst) COMD=zstd ;;
	*) quit ;;
	esac
	$COMD -dc <"$IN" | tar ${OUT:+-C "$OUT"} -xf - $FILES
	;;
*.7z)
	[ "$FILES" ] && m=e || m=x
	7z $m ${OUT:+-o"$OUT"} "$IN" $FILES
	;;
*.zip) unzip "$IN" ${OUT:+-d "$OUT"} $FILES ;;
*) quit ;;
esac

exit $?
