#!/bin/bash

# This script installs all in rootfs/ and triggers all in triggers/

if [ "$1" ]; then "$GEARLIB"/sysup/mount "$1" || exit 1; fi

for zip in "$GEARDATA"/extension/*.zip; do
	"$GEARLIB"/compat/flashablezip/install "$zip"
done

for gxp in "$GEARDATA"/extension/*.gxp.tar*; do
	"$GEARLIB"/compat/gearlockgxp/install "$gxp"
done

if [ "$1" ]; then "$GEARLIB"/sysup/unmount "$1" || exit 1; fi

