#!/bin/sh

mount_gearlock() {
	mkdir -p "$1"

	case "$GEARLOCK" in
	/dev/* | UUID=* | LABEL=*)
		GEARLOCK=$(find_mnt "$GEARLOCK")
		GEARLOCKFS=$(fs_type "$GEARLOCK")
		mount -t "$GEARLOCKFS" "$GEARLOCK" "$1" || return 1
		;;
	*)
		GEARLOCK_IMG=$2/$SRC/$GEARLOCK
		case "$GEARLOCK" in
		*.img) mount -o loop,noatime "$GEARLOCK_IMG" "$1" || return 1 ;;
		*) mount --bind "$GEARLOCK_IMG" "$1" ;;
		esac
		;;
	esac

	case "$BOOT_PART" in
	/dev/* | UUID=* | LABEL=*)
		BOOT_PART=$(find_mnt "$BOOT_PART")
		mount -t "$(fs_type "$BOOT_PART")" "$BOOT_PART" "$1"/boot || return 1
		;;
	*) mount --bind "$2/$SRC/$BOOT_PART" "$1"/boot ;;
	esac

	mountpoint -q "$2" && mount --bind "$2" "$1"/gearroot
}

run_latehook() {
	GEARLOCK=${GEARLOCK:-gearlock.img}

	mount_gearlock /gearlock /mnt

	[ "$MODE" = recovery ] && /gearlock/bin/bootless-chroot

	mkdir -p /android/data/gearlock
	mount --move /gearlock /android/data/gearlock

}
