#!/bin/sh

mount_gearlock() {
	mkdir -p "$1"

	case "$GEARLOCK" in
	/dev/* | UUID=* | LABEL=*)
		GEARLOCK=$(find_mnt "$GEARLOCK")
		GEARLOCKFS=$(fs_type "$GEARLOCK")
		mount -t "$GEARLOCKFS" "$GEARLOCK" "$1" || return 1
		;;
	*)
		GEARLOCK_IMG=$2/$SRC/$GEARLOCK
		case "$GEARLOCK" in
		*.img) mount -o loop,noatime "$GEARLOCK_IMG" "$1" || return 1 ;;
		*) mount --bind "$GEARLOCK_IMG" "$1" ;;
		esac
		;;
	esac

	mountpoint -q "$2" && mount --bind "$2" "$1"/gearroot
}

run_hook() {
	GEARLOCK=${GEARLOCK:-gearlock.img}

	mount_gearlock /gearlock /mnt

	/gearlock/bin/bootless-chroot pre /usr/bin/run-gqueue
	/gearlock/bin/bootless-chroot pre /usr/bin/gearload

	[ "$MODE" = recovery ] && /gearlock/bin/bootless-chroot pre
}

run_latehook() {
	mount --bind "/gearlock/lib/modules" /android/system/lib/modules
	mount --bind "/gearlock/lib/firmware" /android/system/lib/firmware

	[ -e /gearlock/var/gearlock/initialized ] ||
		/gearlock/bin/bootless-chroot /usr/share/gearlock/first-interation.sh

	mkdir -p /android/data/gearlock
	mount --move /gearlock /android/data/gearlock

}

