#!/bin/sh

live_system_mount_handler() {
	# in live mode, SRC, SYSTEM, DATA, GEARLOCK are ignored
	export SRC='' SYSTEM=system.img GEARLOCK=gearlock.img

	local remount_limit=0 disktmp
	while [ ! "$ROOT" ] && [ "$remount_limit" -le 5 ]; do
		remount_limit=$((remount_limit + 1))
		for dev in /dev/[hmnsv][dmrv][0-9a-z]* /dev/xvd[0-9a-z]* /dev/nvme[0-9]n[0-9]p[0-9a-z]* /dev/mmcblk[0-9]p[0-9a-z]*; do
			[ -e "$dev" ] || continue
			sleep 1
			disktmp="$(mktemp)"
			rm -f "$disktmp"
			mkdir -p "$disktmp"
			timeout 10 mount -t auto "$dev" "$disktmp"
			[ -d "$disktmp/$SYSTEM" ] &&
				ROOT=$dev
			umount -lf "$disktmp"
			[ "$ROOT" ] && break
		done
	done

	[ "$ROOT" ] || launch_shell "No ROOT device found!"

	system_mount_handler "$ROOT"
}

empty_data() { mount -t tmpfs tmpfs /android/data; }

run_hook() {
	for mod in dm_mod dm-raid raid0 raid1 raid456 loop; do
		modprobe $mod || true
	done

	export system_mount_handler=live_system_mount_handler
	export data_mount_handler=empty_data
}
