#!/bin/bash

# failsafe
[ "$1" ] || return

. "$GXP_DB/$1/info"

for prov in $PROVIDES; do
  [ -h "$GXP_DB/$prov" ] && unlink "$GXP_DB/$prov"
done

unset NAME VERSION DESC ARCH LICENSE AUTHOR URL PROVIDES DEPENDS FILEONHOST

while read -r file; do
  [ -d "$workd/$file" ] && [ "$(ls -A "$workd/$file")" ] && continue
  rm -rf "$workd/$file"
done <<<"$(tac "$GXP_DB/$1/files")"

rm -rf "$GXP_DB/$1"
