#!/bin/bash

# failsafe
[ "$1" ] || return

if grep -q " ROOT=" /proc/cmdline 2>/dev/null; then
  TMPDIR=$SRCDIR/tmp
  [ -d "$TMPDIR" ] || mkdir -p "$TMPDIR"
else
  TMPDIR=/data/local/tmp
fi

workd="$TMPDIR/pkg"
rm -rf "$workd"
mkdir -p "$workd"
"$GEARLIB"/extract "$1" "$workd"

installed=
while read -r file; do
  [ -d "$workd/$file" ] && mkdir -p "/$file" && continue

  installed="$installed $file"
  if ! mv -f "$workd/$file" "/$file"; then
    error=true
    break
  fi
done <"$workd/files"

if [ "$error" ]; then
  rm -rf $installed
  exit 1
fi

. "$workd/info"

mkdir -p "$GXP_DB/$NAME"
mv -f "$workd/info" "$GXP_DB/$NAME"
mv -f "$workd/files" "$GXP_DB/$NAME"

for prov in $PROVIDES; do
  [ -e "$GXP_DB/$prov" ] || ln -s "$NAME" "$GXP_DB/$prov"
done

if [ "$explicit" = true ]; then
  grep -q "$NAME" /etc/gxp.explicit || echo "$NAME" >>/etc/gxp.explicit
fi

unset NAME VERSION DESC ARCH LICENSE AUTHOR URL PROVIDES DEPENDS FILEONHOST
