#!/bin/bash

provide_list=
tmp_depend_list=
total_install=
remove_list=
conflicts=
instfile=
instsize=0
for pkg in "$@"; do
  temp=$(mktemp -q)
  "GEARLIB"/extract "$pkg" "$temp" info

  . "$temp/info"
  pkgname=$NAME

  if echo "$provide_list" | grep -q "$NAME"; then
    echo "Package conflict detected" && exit
  fi

  for subpkg in $DEPENDS; do
    if [ ! -d "$GXP_DB/$subpkg" ]; then
      tmp_depend_list="$tmp_depend_list $subpkg"
    fi
  done

  for subpkg in $PROVIDES; do
    if [ -d "$GXP_DB/$subpkg" ]; then
      conflicts="$conflicts $subpkg"
    else
      provide_list="$provide_list $subpkg"
    fi
  done

  unset NAME VERSION DESC ARCH LICENSE AUTHOR URL PROVIDES DEPENDS FILEONHOST

  for subpkg in $conflicts; do
    depbreak=
    for installed in "$GXP_DB"/*/; do
      . "$installed/info"
      if echo "$DEPENDS" | grep -q "$subpkg"; then
        depbreak="$depbreak,$(basename "$installed")"
      fi
      unset NAME VERSION DESC ARCH LICENSE AUTHOR URL PROVIDES DEPENDS FILEONHOST
    done
    read -rn 1 -p "$pkgname conflicts with $subpkg. Remove $subpkg? [Y/n]" confirm
    case "$confirm" in
    [Yy]) if [ "$depbreak" ]; then
      echo "Remove $subpkg breaks dependency of ${depbreak#,}"
      exit 1
    else
      remove_list="$remove_list $subpkg"
    fi ;;
    *) exit 1 ;;
    esac
  done

  total_install="$total_install $pkgname"
  instfile="$instfile $pkg"
  instsize=$((instsize + $("$GEARLIB"/decompsize "$pkg")))
done

depend_list=
for deps in $tmp_depend_list; do
  if echo "$provide_list" | grep -q "$deps"; then
    continue
  fi
  depend_list="$depend_list $deps"
done

if [ "$depend_list" ]; then
  sync false $depend_list
fi

if [ "$remove_list" ]; then
  remove $remove_list
fi

echo
echo "Packages to be installed: $total_install"
echo "Total installed size: $((instsize / 1024))Mb"
read -rn 1 -p "Perform installation? [Y/n]" confirm
case "$confirm" in
[Yy]) ;;
*) exit 0 ;;
esac

explicit=true
for pkg in $instfile; do
	"$GEARLIB"/gxp/installfile "$pkg" || exit 1
done
