#!/bin/bash

die() { echo "$*" && exit 1; }

NEWIMG=$1
NEWIMGSIZE=$(du -sk "$NEWIMG" | awk '{print $1}')
shift

case "$SYSTEM_TYPE" in
?fs | img) COMP=".$SYSTEM_TYPE" ;;
esac

other() { THE_OTHER=$SRCDIR/system_$1$COMP; }

echo "$SYSTEM" | grep -E '_a(\.(img|[se]fs))?$' && other b || other a

[ -e "$THE_OTHER" ] && rm -rf "$THE_OTHER"

FREESPACE=$(/usr/lib/gearlock/checkfree)

((NEWIMGSIZE > FREESPACE)) &&
  die "Not enough space to update system image"

mv "$NEWIMG" "$THE_OTHER"
