#!/bin/bash

die() { echo "$*" && exit 1; }

NEWIMG=$1
NEWIMGSIZE=$(du -sk "$NEWIMG" | awk '{print $1}')
shift

checkspace() {
  ((NEWIMGSIZE > FREESPACE)) &&
    die "Not enough space to update system image"
}

case "$SYSTEM" in
/dev/*)
  SYSTEM=$(resolve_device "$SYSTEM")
  FREESPACE=$(($(lsblk -dnbo SIZE "$SYSTEM") / 1024))
  checkspace

  if [ "$BOOTED" ]; then
    die "Cannot live replace system image"
  else
    dd if="$NEWIMG" of="$SYSTEM" bs=1M status=progress
  fi
  ;;
*)
  case "$SYSTEM_TYPE" in
  ?fs | img) COMP=".$SYSTEM_TYPE" ;;
  esac

  SYSTEM=$SRCDIR/system$COMP
  FREESPACE=$(/usr/lib/gearlock/checkfree)
  checkspace

  if [ "$BOOTED" ]; then
    mv -r "$SYSTEM" "$SYSTEM-pending_remove"
  else
    rm -rf "$SYSTEM"
  fi
  mv "$NEWIMG" "$SYSTEM"
  ;;
esac
