#!/bin/bash

die() { echo "==> ERROR: $1" >&2 && quit "${2:-1}"; }

quit() {
	cd "$CURRENT_DIR"
	rm -rf "$TMPDIR"
	exit "$1"
}

DIR=$1

CURRENT_DIR=$(pwd)
cd "$DIR"

case "$DIR" in
legacy-*.gxp)
	export PATH=$GEARLIB/compat/gearlockgxp/toolchain:$PATH
	. '!zygote.sh'
	;;
esac

./install.sh ||
	die "Failed to install '$FILE'" 1

quit 0

# TODO: make overlayfs
